FROM node:16

# Create a working directory in the container and make it the current dir
WORKDIR /usr/src/app

COPY ./src/app-server/package*.json .
COPY ./src/app-server/tsconfig.json .
COPY ./src/app-server/geo.ts ./server/geo.ts
COPY ./src/firebase-backend.ts .
RUN npm install && (cd /usr/src/app && npx tsc)

EXPOSE 4000

CMD ["node", "server/geo.js"]