#
# To build the image locally, run the following command from the PARENT of this directory
#
# docker build -f Dockerfile.web .

FROM node:14

# Create a working directory in the container and make it the current dir
WORKDIR /usr/web/app
COPY backend/package.json .
COPY backend/tsconfig.json .

# For the two .ts files below, it is important to copy them
# and mimic the actual structure on the local directory
# /usr/web/app/server/geo.ts
# /usr/web/app/src/firebase-backend.ts
COPY backend/geo.ts server/geo.ts
COPY src/firebase-backend.ts ./src/firebase-backend.ts

RUN npm install && (cd /usr/web/app && npx tsc)

# Ignored on Heroku
EXPOSE $PORT

CMD ["node", "server/geo.js"]