Expr ::= Expr '+' Term | Expr '-' Term | Term
Term ::= Term '*' Power | Term '/' Power | Power
Power ::= Factor '^' Power | Factor
Factor ::= '(' Expr ')' | Expr | Number | Ident
Number ::= Digit Number | Digit
