import { h} from "vue";
import IconBase from "@/components/IconBase.vue";

const iconNames = [
  "earthPoint",
  "angle",
  "angleBisector",
  "antipodalPoint",
  "applyTransformation",
  "appSettings",
  "calculationObject",
  "circle",
  "clearConstruction",
  "constructionsTab",
  "earthTab",
  "coordinate",
  "copyToClipboard",
  "cycleNodeValueDisplayMode",
  "delete",
  "deleteConstruction",
  "deleteNode",
  "downloadConstruction",
  "earthLatitude",
  "earthLongitude",
  "earthPoint",
  "ellipse",
  "hide",
  "hideNode",
  "hideNodeLabel",
  "iconFactory",
  "intersect",
  "inversion",
  "line",
  "measuredCircle",
  "measurementObject",
  "measurePolygon",
  "measureTriangle",
  "midpoint",
  "move",
  "notifications",
  "nSectLine",
  "nSectPoint",
  "objectsTab",
  "parametric",
  "perpendicular",
  "point",
  "pointDistance",
  "pointOnObject",
  "pointReflection",
  "polar",
  "redo",
  "reflection",
  "rotate",
  "rotation",
  "segment",
  "segmentLength",
  "select",
  "shareConstruction",
  "showNode",
  "showNodeLabel",
  "slider",
  "styleDrawer",
  "tangent",
  "threePointCircle",
  "toggleLabelDisplay",
  "toolsTab",
  "transformedCircle",
  "transformedEllipse",
  "transformedLine",
  "transformedPoint",
  "transformedSegment",
  "translation",
  "undo",
  "zoomFit",
  "zoomIn",
  "zoomOut",
  "starConstruction",
  "unstarConstruction",
  "privateConstruction"
];

const toRecord = (n: Array<string>): Record<string, any> => {
  return n.reduce(
    (acc: Record<string, any>, curr: string, pos: number) => {
      return {
        ...acc,
        [curr]: () => h(IconBase as any, { iconName: curr })
      };
    },
    {} as Record<string, any>
  );
};
export const customIcons = toRecord(iconNames);
