declare module "splitpanes";
declare module "vue-advanced-cropper";
declare module "newton-raphson-method";
declare module "node-gzip";
declare module "lodash.clonedeep";
declare module "gifencoder";
declare module "png-file-stream";
//declare module "save-svg-as-png";
//declare module "types-save-svg-as-png";