declare module "splitpanes";
declare module "vue-advanced-cropper";
declare module "newton-raphson-method";
declare module "node-gzip";
declare module "lodash.clonedeep";
declare module "gif.js";
declare module "vuetify/lib/util/colors";
declare module "vue-cesium/global";
declare module "vue-cesium/Cesium"
//declare module "save-svg-as-png";
//declare module "types-save-svg-as-png";
